fix: Fix `git` Hooks
Also patch `nom` Rendering

diff --git a/files/git/hooks/commit-msg b/files/git/hooks/commit-msg
--- a/files/git/hooks/commit-msg
+++ b/files/git/hooks/commit-msg
@@ -2,14 +2,15 @@
 error() { echo -e "\033[0;31merror:\033[0m $1"; exit 7; }
 
 ## Commit Message ##
-# Keywords
-if ! head -1 "$1" | grep -qE "^(feat|fix|ci|blog|chore|docs|test|style|refactor)(\(.+?\))?\!?: .{1,}$"
+
+# 1. Structure
+if ! head -n 1 "$1" | grep -qE '^(feat|fix|ci|blog|chore|docs|test|style|refactor)(\([^)]+\))?!?: .+$'
 then
-  error "Commit Message is invalid"
+  error "Commit Message header is invalid\nFormat -> type(scope): subject"
 fi
 
-# Length
-if ! head -1 "$1" | grep -qE "^.{1,50}$"
+# 2. Length
+if ! head -n 1 "$1" | grep -qE '^.{1,50}$'
 then
-  error "Commit Message is too long"
+  error "Commit Message header is too long\nGreater than 50 characters"
 fi
diff --git a/files/git/hooks/pre-commit b/files/git/hooks/pre-commit
--- a/files/git/hooks/pre-commit
+++ b/files/git/hooks/pre-commit
@@ -2,8 +2,9 @@
 error() { echo -e "\033[0;31merror:\033[0m $1"; exit 7; }
 
 ## Pre-Commit Checks ##
+
 # Nix Syntax
-if [ "$(find . -name '*.nix' 2>/dev/null | wc -l)" != 0 ]
+if [ "$(find . -name 'flake.nix' 2>/dev/null | wc -l)" != 0 ]
 then
-  nix flake check || error "Invalid Syntax"
+  nix flake check || error "Invalid Nix Flakes Configuration"
 fi
